### ISSUE TITLE
[Prisma]: Move Schema File to API

### ISSUE THREAD

**Issue by johannesschobel** [nxpm/stack#100]
Dear @beeman ,

with respect to my issue #66 , which deals with multiple APIs within the monorepository, i stumbled upon the following issue:
Currently, the `schema.prisma` file is located within a library folder. However, with respect to multiple APIs, this schema file should be moved to the dedicated application (i.e., the `apps/api1` folder), i guess.

What do you think?

All the best

**Comment by beeman** [comment]
Hi @johannesschobel, one of the best practices with Nx that Nxpm promotes is to keep the apps as tiny as possible. This is the reason almost everything that gets generated lives in libs.

With that said, nxpm creates the project for you and after that it's up to the developer on how to structure it, so having tiny apps is a recommendation and best practice, but it's not forced.

I think the things to keep in mind around having multiple prisma files in a project don't change when it would change the location from libs to apps.

Right now, if you would create a second api, it will get it's own schema created in it's own lib.

The main thing that makes it difficult, is that the `prisma` command only expects one file per project. It will either look for `prisma/schema.prisma`, the value of `prisma.schema` in package json or you need to specify the file path with the command.

Another thing to keep in mind is that both api projects will use the same environment variable by default, `DATABASE_URL`.

I have been thinking about using the Nx Workspace file for wire up some Prisma commands, but this is something that might come in the future as part of an Nx-Prisma integration. But that's definitely something I would recommend looking at, probably starting by using [run-commands](https://nx.dev/latest/angular/plugins/workspace/executors/run-commands).

I hope this answers your question.
