### ISSUE TITLE
Feature: Migration to Eslint

### ISSUE THREAD

**Issue by ruslanguns** [nxpm/stack#52]
As tslint is deprecated we need to migrate to Eslint

**Comment by beeman** [comment]
This is a great point @ruslanguns! 

A quick fix to get this in, might be defining the linter [here](https://github.com/nxpm/stack/blob/main/packages/stack/src/schematics/web/schematic-web.ts#L96-L100
) to make sure the app gets generated with that, and [here](https://github.com/nxpm/stack/blob/main/packages/stack/src/schematics/web-lib/schematic-web-lib.ts#L16-L26) for all the libraries that generated.

If you're up to giving it a shot, more than welcome to review/help merge any PR's.

**Comment by beeman** [comment]
Btw I am looking at migrating this project to a new Nx 11 structure (where schematics are generators), which would have this by default.

**Comment by ruslanguns** [comment]
> This is a great point @ruslanguns!
> 
> A quick fix to get this in, might be defining the linter [here](https://github.com/nxpm/stack/blob/main/packages/stack/src/schematics/web/schematic-web.ts#L96-L100) to make sure the app gets generated with that, and [here](https://github.com/nxpm/stack/blob/main/packages/stack/src/schematics/web-lib/schematic-web-lib.ts#L16-L26) for all the libraries that generated.
> 
> If you're up to giving it a shot, more than welcome, I'm happy to review/help merge any PR's.

Nice feedback, looks like it is just to add a command right there to point to eslint. Will send you the PR soon.


>Btw I am looking at migrating this project to a new Nx 11 structure (where schematics are generators), which would have this by default.

I just got noticed about this change, I never use schematics, looks like they are powerful. I will try to learn by using your nxpm stack project there is a beautiful work around.
