### ISSUE TITLE
Creating a new project should leave the user with a clean git repo.

### ISSUE THREAD

**Issue by beeman** [nxpm/stack#55]
## Expected Behavior

After creating a new project with nxpm-stack init, the git repo should be clean.

## Current Behavior

The git repo has (a lot of) unstaged changes. Everything that gets added after a new `yarn create nx-workspace`.

## Possible Solution

[An attempt](https://github.com/nxpm/stack/blob/9474780edd62e2f5e6faaa27f290062acdbaca49/packages/stack/src/schematics/init/schematic-init.ts#L136-L140) was made.... but this is not it.

Probably something like `execSync('git add -a && git commit')` will work.

## Steps to Reproduce (for bugs)

1. Create a new project
2. Run `git status` in the new project

## Context

Ideally, we'd not use `yarn create nx-workspace` and append to that, but basically replace @nrwl/workspace with a custom workspace layout.

That's a lot of work and potential maintenance so for now adding an extra commit is the quick win.

**Comment by ruslanguns** [comment]
Great idea ! 

You could do it like in angular cli option flag on update e.g. `ng update <package> -C`:

```
--create-commits (-C)
    Create source control commits for updates and migrations.
```

Commit can run by default when creating the stack and can be opt-out for those won't want it. The opt-out should affect also the NX Workspace.

Commit can also be opt-in when performing generate commands... It would be ideal if there is an exception to request that the repository must be clean of uncommitted changes.

**Comment by ruslanguns** [comment]
@beeman how about rewritting history running the command: `git commit --amend -CHEAD`

It will look like: 
![image](https://user-images.githubusercontent.com/19806968/104976387-00c98b00-59f5-11eb-8cc1-be92a9fb5b31.png)

**Comment by beeman** [comment]
@ruslanguns yes, for a quick fix this will work! Feel free to send a PR!
