### ISSUE TITLE
Replace NX's README.md by the NXPM one

### ISSUE THREAD

**Issue by ruslanguns** [nxpm/stack#60]
## Expected Behavior

It would be better to have NXPM README.md instead of the NX one since there are some instructions that are necessary.

## Current Behavior

Currently the README.md is the one provided by the NX workspace.

## Possible Solution

Replace README.md

**Comment by beeman** [comment]
This is a great point. 

As a start, I think it would be nice to list similar instructions to those are currently printed after installation:

```
>  NXPM   INFO  Installation finished
>  NXPM   INFO  To get started         : cd my-stack
>  NXPM   INFO  Start database servers : docker-compose up
>  NXPM   INFO  Run setup              : yarn setup
>  NXPM   INFO  Start API              : yarn dev:api
>  NXPM   INFO  Start Web              : yarn dev:web
``` 

And probably a link to Nx' documentation. And very open for other suggestions.

**Comment by ruslanguns** [comment]
@beeman definitely an awesome idea!
