### ISSUE TITLE
Generated AuthStore needs to verify authenticated connection after login/register

### ISSUE THREAD

**Issue by beeman** [nxpm/stack#62]
## Expected Behavior

After login or register, the authenticated connection should verified by retrieving the `me` Query.

## Current Behavior

The session is not verified. When a login success but somehow the cookie does not get set, the session is invalid and will not work. This should be prevented by checking the session.

## Steps to Reproduce (for bugs)

1. Deploy a generated app on Heroku
2. By default, cookie will not be set because of missing `API_COOKIE_DOMAIN` env var.
3. Register: the UI will let you in, you won't have a session

**Comment by ruslanguns** [comment]
+1

**Comment by beeman** [comment]
Fixed [here](https://github.com/nxpm/stack/commit/ebc4c9a550dbc049ef559a152c82c7bbeeb64cf1#diff-0fa328504e3055625a7ba1ee853a8dce8cd63906d759684f9859900602f3b13d).
