### ISSUE TITLE
Duplicated code that can be removed

### ISSUE THREAD

**Issue by ruslanguns** [nxpm/stack#63]
## Expected Behavior

There is some unused code in the ApiCore libraries as well few files that are unnecesary. 

## Possible Solution

In my working example I have committed the changes with all the unnecessary code I saw. If you are interested I can submit a PR with the code removed:

https://github.com/ruslanguns/nxpm-app-sample/commit/36ce047cef34a1aaf79c0f07e73ff49d519644c4

## Steps to Reproduce (for bugs)

By generating a new workspace.

## Your Environment

- Version used: `nxpm-stack --version 4.4.4`
- Browser Name and version: N/A
- Operating System and version (desktop or mobile): N/A
- Link to your project: N/A

**Comment by beeman** [comment]
Hey @ruslanguns , feel free to add a PR that removes unused code.
