### ISSUE TITLE
Rename  DATA-ACCESS Library Type

### ISSUE THREAD

**Issue by johannesschobel** [nxpm/stack#65]
Dear @beeman ,

i noticed, that the `data-access` library type results in folder names like this: `libs/api/foobar/data-access/...` and respective module is named like this: `api-foobar-data-access.module.ts`,

Modules for other types (i.e, `ui` or `feature`), however, are called `api-foobar-feature.module.ts`.

The `feature` Module has 3 parts, whereas the `Data-Access` Module has 4 parts.
Maybe we can align those library types by just using `data` instead of `data-access`?
What do you think?

All the best

**Comment by beeman** [comment]
Hey @johannesschobel. I agree that it's a bit odd compared to the rest, but I think for now I'll leave `data-access` as I think it's a better name than `data`. For me, `data` points to the data itself, whereas `data-access` is a better description.

The name `data-access` is the recommended name by Nrwl in their [book Angular Enterprise Monorepo Patterns](https://go.nrwl.io/angular-enterprise-monorepo-patterns-new-book), this stack currently follows that pattern.

Going to close the issue for now. If at some point the project matured enough where it's easy to make this a configurable option, I definitely want to consider it. Currently, it'll be an opinionated decision.

I hope you understand.

**Comment by johannesschobel** [comment]
Dear @beeman , thanks a lot for your time to clarify this issue. I understand :+1:
